version: '3'
services:
    app:
        build:
            context: ./node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
            # - /usr/src/app/node_modules # volume anonimo
        tty: true
        depends_on:
            - db

    db:
        build: ./banco
        container_name: db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: nodedb
            MYSQL_PASSWORD: MainPassword
        restart: always
        tty: true
        volumes:
        - ./mysl:/var/lib/mysql
        networks:
            - node-network
    nginx:
        build: ./nginx
        container_name: nginxreverso
        ports:
            - "8080:80"
        networks:
            - node-network
        depends_on:
            - app

networks:
    node-network:
        driver: bridge
        